name: Frontend

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-24.04

    defaults:
      run:
        working-directory: KempIS Frontend

    steps:
    - name: Configure git
      working-directory: .
      run: |-
        git config --global core.autocrlf false
        git config --global core.eol lf

      - uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm

      - name: Install packages
        run: npm ci

      - name: Check linting rules
        run: npm run lint

      - name: Build
        run: npm run build
